project:
  type: book
  output-dir: "docs" # 输出（编译后的HTML文件、PDF文件以及运行code chunk后产生的图像、数据等）文件夹
  execute-dir: project
editor: visual

book:
  title: "R语言学习笔记"
  subtitle: "从数据清洗到高级统计学和生物信息学"
  navbar:
    logo: images/logo.jpg
    background: "#f1f1f3" # 顶栏背景色（默认为primary，网页主色）
    foreground: "black" # 导航栏字体颜色
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Introduction"
        file: intro.qmd
      - text: "Parts"
        menu:
          - r_basic/r_basics.qmd
          - single_cell/seurat.qmd
          - quarto_foundation/quarto_foundation.qmd
      - file: references.qmd
    right:
      - icon: book-fill
        text: Bookdown
        url: https://bookdown.org
  chapters:
    - text: 主页
      file: index.qmd
    - intro.qmd
    - text: "---" # 添加分割线
    - part: r_basic/r_basics.qmd
      chapters:
        - r_basic/environment_configuration.qmd
        - r_basic/data_input_output.qmd
    - part: single_cell/seurat.qmd
      chapters:
        - single_cell/seurat_command_list.qmd
        - single_cell/seurat_tutorial.qmd
        - single_cell/data_visualization_methods_in_seurat.qmd
        - single_cell/sctransform.qmd
        - single_cell/integration.qmd
        - single_cell/integrative_analysis_in_seurat_v5.qmd
        - single_cell/mapping_and_annotating_query_datasets.qmd
        - single_cell/cell_cycle_regression.qmd
        - single_cell/de_vignette.qmd
    - part: quarto_foundation/quarto_foundation.qmd
      chapters:
        - quarto_foundation/yaml_settings.qmd
        - quarto_foundation/images_settings.qmd
        - quarto_foundation/cross_references.qmd
        - quarto_foundation/insert_other_content.qmd
        - quarto_foundation/quarto_books.qmd
        - quarto_foundation/github_pages.qmd
    - text: "---"
    - part: "参考文献"
      chapters:
        - references.qmd
  sidebar:
    style: "docked" # “docked” and “floating”
    collapse-level: 1 # 导航栏初始显示多少级标题
  page-navigation: true # 打开右侧的页内标签
  repo-actions: [source, issue, edit] # 在页面右侧显示导航到GitHub仓库的链接
  repo-url: https://github.com/djhcod/r-notes # GitHub仓库的链接
  search:
    location: navbar
    type: overlay
  page-footer:
    left:
      - text: "This book was built with Quarto"
    center: "Copyright 2023, Du Junhong"
    right:
      - icon: github
        href: https://github.com/djhcod
    border: true
  favicon: images/logo.jpg # 网页的logo
  twitter-card: true
  site-url: https://djhcod.github.io/r-notes/
  sharing: [twitter, facebook] # 显示分享到社交网络图标
  comments:
    hypothesis:
      theme: classic
      openSidebar: false
      showHighlights: always
      enableExperimentalNewNoteButton: true
    utterances:
      repo: https://github.com/djhcod/r-notes

format:
  html:
    theme:
      light: Flatly # 分别设置暗色主题和亮色主题
      dark: darkly
    embed-resources: false # 是否将所有源文件嵌入HTML文件
    code-tools: true
    code-link: true
    anchor-sections: true # 是否显示章节锚点图标（便于复制直接定位到某个章节的链接）
    link-external-newwindow: true # 是否在新窗口打开链接
    toc-depth: 3 # 设置右侧目录显示的最低层级（默认为显示到3级标题）
    toc-expand: 1 # 右侧目录在一开始显示到多少级，默认显示到一级标题。

execute:
  eval: true
  warning: false
  cache: true # 开启运算结果缓存。将会在文件目录中生成后缀“_cache”的文件夹。

number-sections: true # 是否开启章节编号
number-depth: 2 # 标题编号级数

crossref:
  subref-labels: alpha A # 次级引用编号类型，如组图中的小图（默认是小写字母：alpha a）

fig-align: left

bibliography: references.bib # 参考文献目录


