project:
  type: website
  output-dir: "docs" # 输出（编译后的HTML文件、PDF文件以及运行code chunk后产生的图像、数据等）文件夹
  execute-dir: project
editor: visual

execute:
  eval: true
  warning: false
  cache: true # 开启运算结果缓存。将会在文件目录中生成后缀“_cache”的文件夹。
  freeze: auto

number-sections: true # 是否开启章节编号
number-depth: 2 # 标题编号级数

fig-align: left

crossref:
  subref-labels: alpha A # 次级引用编号类型，如组图中的小图（默认是小写字母：alpha a）

bibliography: references.bib # 参考文献目录

language:
  search-box-placeholder: Search

website:
  title: "R语言学习笔记：从数据清洗到高级统计学和生物信息学"
  page-navigation: true
  reader-mode: true
  favicon: images/logo.jpg # 网页的logo
  twitter-card: true
  google-analytics: "G-G2HZEXHNCE"
  site-url: https://djhcod.github.io/r-notes/
  repo-url: https://github.com/djhcod/r-notes # GitHub仓库的链接
  repo-actions: [source, issue] # 在页面右侧显示导航到GitHub仓库的链接
  open-graph: true
  search:
    location: navbar
    type: textbox # overlay or textbox



  navbar:
    logo: images/logo.jpg
    title: "R语言学习笔记"
    background: light # 顶栏背景色（默认为primary，网页主色）
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - r_basic/r_basics.qmd
      - text: "单细胞数据分析"
        menu:
          - text: "单细胞数据分析介绍"
            file: single_cell/single_cell_intro.qmd
          - single_cell/seurat/seurat_intro.qmd
          - single_cell/scRNA-seq_online/00_intro.qmd
          - single_cell/sc_supplementary/sc_supplementary_intro.qmd
      - quarto_foundation/quarto_foundation.qmd

    right:
      - icon: book-fill
        text: Bookdown
        url: https://bookdown.org

    tools:
      - icon: github
        href: https://github.com/djhcod/r-notes

  sidebar:
    style: docked # “docked” and “floating”
    border: true
    search: false
    collapse-level: 2 # 导航栏初始显示多少级标题

    contents:
      - text: 主页
        file: index.qmd
      - section: r_basic/r_basics.qmd
        contents:
          - r_basic/environment_configuration.qmd
          - r_basic/data_input_output.qmd
          - r_basic/basic_data_function.qmd
          - r_basic/dplyr.qmd
          - r_basic/character.qmd
          - r_basic/loop.qmd
      - section: single_cell/single_cell_intro.qmd
        contents:
          - single_cell/scRNA-seq_intro.qmd
          - single_cell/generation_of_count_matrix.qmd
          - section: single_cell/seurat/seurat_intro.qmd
            contents:
              - single_cell/seurat/seurat_command_list.qmd
              - single_cell/seurat/seurat_tutorial.qmd
              - single_cell/seurat/data_visualization_methods_in_seurat.qmd
              - single_cell/seurat/sctransform.qmd
              - single_cell/seurat/cell_cycle_regression.qmd
              - single_cell/seurat/integration.qmd
              - single_cell/seurat/integrative_analysis_in_seurat_v5.qmd
              - single_cell/seurat/marker_gene_identification.qmd
              - single_cell/seurat/de_vignette.qmd
              - single_cell/seurat/mapping_and_annotating_query_datasets.qmd
          - section: single_cell/scRNA-seq_online/00_intro.qmd
            contents:
              - single_cell/scRNA-seq_online/03_SC_quality_control-setup.qmd
              - single_cell/scRNA-seq_online/04_SC_quality_control.qmd
              - single_cell/scRNA-seq_online/postQC_workflow.qmd
              - single_cell/scRNA-seq_online/05_theory_of_PCA.qmd
              - single_cell/scRNA-seq_online/06_SC_SCT_normalization.qmd
              - single_cell/scRNA-seq_online/06_integration.qmd
              - single_cell/scRNA-seq_online/07_SC_clustering_cells_SCT.qmd
              - single_cell/scRNA-seq_online/08_SC_clustering_quality_control.qmd
              - single_cell/scRNA-seq_online/09_merged_SC_marker_identification.qmd
          - section: single_cell/sc_supplementary/sc_supplementary_intro.qmd
            contents:
              - single_cell/sc_supplementary/read_sc_data.qmd
              - single_cell/sc_supplementary/universal_marker.qmd
              - single_cell/sc_supplementary/integrated_analysis_multiple_single_cell_datasets_1.qmd
              - single_cell/sc_supplementary/integrated_analysis_multiple_single_cell_datasets_2.qmd
              - single_cell/sc_supplementary/DecontX.qmd
      - section: quarto_foundation/quarto_foundation.qmd
        contents:
          - quarto_foundation/yaml_settings.qmd
          - quarto_foundation/images_settings.qmd
          - quarto_foundation/cross_references.qmd
          - quarto_foundation/insert_other_content.qmd
          - quarto_foundation/quarto_shiny.qmd
          - quarto_foundation/quarto_books.qmd
          - quarto_foundation/github_pages.qmd

  page-footer:
    left:
      - text: "This website was built with Quarto"
    center: "Copyright 2024, Du Junhong"
    right:
      - icon: github
        href: https://github.com/djhcod
    border: true


format:
  html:
    theme:
      light: cosmo # 分别设置暗色主题和亮色主题
      dark: darkly
    grid:
      sidebar-width: 250px
    embed-resources: false # 是否将所有源文件嵌入HTML文件
    code-tools: true
    code-link: true
    anchor-sections: true # 是否显示章节锚点图标（便于复制直接定位到某个章节的链接）
    link-external-newwindow: true # 是否在新窗口打开链接
    toc: true
    toc-depth: 3 # 设置右侧目录显示的最低层级（默认为显示到3级标题）
    toc-expand: 1 # 右侧目录在一开始显示到多少级，默认显示到一级标题。
    comments:
      hypothesis:
        theme: classic
        openSidebar: false
        showHighlights: always
        enableExperimentalNewNoteButton: true
      giscus:
        repo: djhcod/r-notes
        input-position: top




